(cl:in-package #:clusters.metric)


(-> earth-mover-metric (t t) single-float)
(defun earth-mover-metric (a b)
  (check-type a (simple-array single-float (*)))
  (check-type b (simple-array single-float (*)))
  (let ((a-length (length a))
        (b-length (length b)))
    (declare (type fixnum a-length b-length))
    (unless (eql a-length b-length)
      (error 'program-error "Sizes of input vectors do not match."))
    (iterate
      (declare (type fixnum i)
               (type single-float sum))
      (for i from 0 below a-length)
      (for distance = (- (+ (the single-float (aref a i))
                            (the single-float prev-distance))
                         (the single-float (aref b i))))
      (for prev-distance previous distance initially 0.0)
      (sum (abs distance) into sum)
      (finally (return sum)))))
