(cl:in-package #:cl-data-structures.utils.metric)


(-> earth-mover-metric ((simple-array single-float (*))
                        (simple-array single-float (*)))
    single-float)
(defun earth-mover-metric (a b)
  (declare (optimize (speed 3) (safety 1) (space 0) (debug 0)))
  (let ((a-length (length a))
        (b-length (length b)))
    (declare (type fixnum a-length b-length))
    (unless (eql a-length b-length)
      (error 'program-error "Sizes of input vectors do not match."))
    (iterate
      (declare (type fixnum i)
               (type single-float sum))
      (for i from 0 below a-length)
      (for distance = (- (+ (the single-float (aref a i))
                            (the single-float prev-distance))
                         (the single-float (aref b i))))
      (for prev-distance previous distance initially 0.0)
      (sum (abs distance) into sum)
      (finally (return sum)))))
